### ISSUE TITLE
add support for `main` branch in the README example

### ISSUE THREAD

**Issue by gregsadetsky** [skywarth/vite-github-pages-deployer#6]
as `main` is the recommended/[default branch name on GitHub](https://github.com/github/renaming), add support for that branch in the example code in the README, i.e. change [this line](https://github.com/skywarth/vite-github-pages-deployer/blob/master/README.md?plain=1#L86) to be

`branches: ["master", "main"]`

**Comment by skywarth** [comment]
Great suggestion. Would you like to open up a PR for the changes ? This way your account would be seen as contributor on the repository.

**Comment by gregsadetsky** [comment]
thank you! just did

**Comment by skywarth** [comment]
Thank you for the contribution.
